config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :institutions, only: [] do
    resources :people do
      member do
        get "parents/search", action: :parent_search, as: :parent_search
        post "parents/:parent_id", action: :relate_parent, as: :relate_parent
      end
      
      resources :enrollments
    end
    
    resources :grades do
      resources :meetings
    end
  end
  
  get "/" => "application#home"
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  validates :name, :year, :institution, presence: true
  validates :name, uniqueness: { scope: :year }
  
  belongs_to :institution
  has_many :enrollments, inverse_of: :grade
  has_many :people, through: :enrollments
  has_many :meetings, inverse_of: :grade
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_institution
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = @institution.grades.all
    
    respond_with(@institution, @grades)
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
    respond_with(@institution, @grade)
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = @institution.grades.create(grade_params)
    
    respond_with(@institution, @grade)
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    @grade.update(grade_params)
    
    respond_with(@institution, @grade)
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy

    respond_with(@institution, @grade)
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = @institution.grades.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:name, :year)
    end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.haml
= simple_form_for([@institution, @grade]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :year

  .form-actions
    = f.button :submit

app/views/grades/edit.html.haml
%h1 Editing grade

= render 'form'

= link_to 'Show', institution_grade_path(@institution, @grade)
\|
= link_to 'Back', institution_grades_path(@institution)

app/views/grades/index.html.haml
%h1 Listing grades

%table
  %thead
    %tr
      %th= t(".name", default: "Name")
      %th= t(".year", default: "Year")
      %th
      %th
      %th

  %tbody
    - @grades.each do |grade|
      %tr
        %td= grade.name
        %td= grade.year
        %td= link_to 'Show', institution_grade_path(@institution, grade)
        %td= link_to 'Edit', edit_institution_grade_path(@institution, grade)
        %td= link_to 'Destroy', institution_grade_path(@institution, grade), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Grade', new_institution_grade_path(@institution)

app/views/grades/new.html.haml
%h1 New grade

= render 'form'

= link_to 'Back', institution_grades_path(@institution)

app/views/grades/show.html.haml
%p= @grade.name
%p= @grade.year

= link_to 'Edit', edit_institution_grade_path(@institution, @grade)
\|
= link_to 'Back', institution_grades_path(@institution)