config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :institutions, only: [] do
    resources :people do
      member do
        get "parents/search", action: :parent_search, as: :parent_search
        post "parents/:parent_id", action: :relate_parent, as: :relate_parent
      end
      
      resources :enrollments
    end
    
    resources :grades do
      resources :meetings
    end
  end
  
  get "/" => "application#home"
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  validates :date, :grade, presence: true
  validates :date, uniqueness: {scope: :grade_id}
  
  belongs_to :grade
  has_many :attendances, inverse_of: :meeting
  has_many :people, through: :attendances
  accepts_nested_attributes_for :attendances
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_institution
  before_action :set_grade
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = @grade.meetings.all
    
    respond_with(@institution, @grade, @meetings)
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    respond_with(@institution, @grade, @meeting)
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
    @grade.people.each do |person|
      @meeting.attendances.build(person: person)
    end
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = @grade.meetings.new(meeting_params)
    @meeting.save

    respond_with(@institution, @grade, @meeting)
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    @meeting.update(meeting_params)
    
    respond_with(@institution, @grade, @meeting)
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    
    respond_with(@institution, @grade, @meeting)
  end

  private
    
    def set_grade
      @grade = @institution.grades.find(params[:grade_id])
    end
     
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = @grade.meetings.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:date, attendances_attributes: [:id, :person_id, :present])
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.haml
= simple_form_for([@institution, @grade, @meeting]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :date
    - @meeting.attendances.each do |attendance|
      = f.simple_fields_for :attendances, attendance do |attendance_fields|
        = attendance_fields.hidden_field :person_id
        = attendance_fields.hidden_field :id
        = attendance.person.name
        = attendance_fields.input :present

  .form-actions
    = f.button :submit

app/views/meetings/edit.html.haml
%h1 Editing meeting

= render 'form'

= link_to 'Show', institution_grade_meeting_path(@institution, @grade, @meeting)
\|
= link_to 'Back', institution_grade_meetings_path(@institution, @grade)

app/views/meetings/index.html.haml
%h1 Listing meetings

%table
  %thead
    %tr
      %th= t(".date", default: "Date")
      %th
      %th
      %th

  %tbody
    - @meetings.each do |meeting|
      %tr
        %td= meeting.date
        %td= link_to 'Show', institution_grade_meeting_path(@institution, @grade, meeting)
        %td= link_to 'Edit', edit_institution_grade_meeting_path(@institution, @grade, meeting)
        %td= link_to 'Destroy', institution_grade_meeting_path(@institution, @grade, meeting), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Meeting', new_institution_grade_meeting_path(@institution, @grade)

app/views/meetings/new.html.haml
%h1 New meeting

= render 'form'

= link_to 'Back', institution_grade_meetings_path(@institution, @grade)

app/views/meetings/show.html.haml
%p= @grade.name
%p= @meeting.date

= link_to 'Edit', edit_institution_grade_meeting_path(@institution, @grade, @meeting)
\|
= link_to 'Back', institution_grade_meetings_path(@institution, @grade)