config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :institutions, only: [] do
    resources :people do
      member do
        get "parents/search", action: :parent_search, as: :parent_search
        post "parents/:parent_id", action: :relate_parent, as: :relate_parent
      end
      
      resources :enrollments
    end
    
    resources :grades do
      resources :meetings
    end
  end
  
  get "/" => "application#home"
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :name, :gender, :institution, presence: true
  validates :gender, inclusion: { in: %w[M m F f] }
  validates :email, uniqueness: { scope: :institution }, allow_blank: true,
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  
  belongs_to :institution
  has_many :enrollments, inverse_of: :person
  has_many :grades, through: :enrollments
  has_many :attendances, inverse_of: :person
  has_many :meetings, through: :attendances

  has_many :parent_children, foreign_key: "parent_id", class_name: "ParentChild"
  has_many :child_parents, foreign_key: "child_id", class_name: "ParentChild"
  has_many :parents, through: :child_parents
  has_many :children, through: :parent_children
  
  scope :exclude, ->(*people){ where.not(id: people) }
  scope :match_last_name, ->(last_name){ where("lower(name) like ?", "%#{last_name.downcase}") }
  scope :name_like, ->(name){ where("lower(name) like ?", "%#{name.downcase}%") }
  
  def last_name
    name.split.last
  end
  
  def probable_parents
    Person.match_last_name(last_name).exclude(self)
  end
  
  def add_parent(person)
    ParentChild.create(child: self, parent: person)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_institution
  before_action :set_person, only: [:show, :edit, :update, :destroy, :relate_parent, :parent_search]

  # GET /people
  # GET /people.json
  def index
    @people = @institution.people.order(id: :desc).all
    
    respond_with(@institution, @people)
  end

  # GET /people/1
  # GET /people/1.json
  def show
    respond_with(@institution, @person)
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = @institution.people.new(person_params)
    @person.save
    
    respond_with(@institution, @person)
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    @person.update(person_params)
    
    respond_with(@institution, @person)
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    
    respond_with(@institution, @person)
  end
  
  def relate_parent
    @parent = @institution.people.find(params[:parent_id])
    @parent_child = @person.add_parent(@parent)
    if @parent_child.valid?
      respond_with(@institution, @person)
    else
      flash[:alert] = @parent_child.errors.full_messages.first
      redirect_to :back
    end
  end
  
  def parent_search
    if (name = params[:name]) && !name.blank?
      @title = t(".search_results", default: "Search results")
      @people = @institution.people.name_like(name)
    else
      @title = t(".possible_parents", default: "Possible parents")
      @people = @person.probable_parents
    end
    
    respond_with(@institution, @people)
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = @institution.people.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :gender, :email, :phone, :date_of_birth)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.haml
= simple_form_for([@institution, @person]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :phone
    = f.input :email
    = f.input :gender, collection: [[t("male", default: "Male"), "M"], [t("female", default: "Female"), "F"]], include_blank: true
    = f.label :date_of_birth
    = f.text_field :date_of_birth

  .form-actions
    = f.button :submit

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', institution_person_path(@institution, @person)
\|
= link_to 'Back', institution_people_path(@institution)

app/views/people/index.html.haml
= link_to 'New Person', new_institution_person_path(@institution)
%br
%h1 Listing people

%table
  %thead
    %tr
      %th= t(".name", default: "Name")
      %th= t(".email", default: "Email")
      %th
      %th
      %th
      %th
      
  %tbody
    - @people.each do |person|
      %tr
        %td= person.name
        %td= person.email
        %td
          %a{href: "#", "data-reveal-id" => "enrollment_form", "data-person-id" => person.id}= "Enroll"
        %td= link_to 'Show', institution_person_path(@institution, person)
        %td= link_to 'Edit', edit_institution_person_path(@institution, person)
        %td= link_to 'Destroy', institution_person_path(@institution, person), :method => :delete, :data => { :confirm => 'Are you sure?' }

#enrollment_form.reveal-modal{"aria-hidden" => "true", "aria-labelledby" => "modalTitle", "data-reveal" => "", :role => "dialog"}
  .form
    = t("loadind_please_wait", default: "Loading. Please wait.")
  %p.message
  %a.close-reveal-modal{"aria-label" => "Close"} ×
  
:javascript
  $("a[data-reveal-id=enrollment_form]").click( function() {
    var person_id = $(this).attr("data-person-id");
    var institution_id = #{@institution.id};
    var form_path = "/institutions/" + institution_id + "/people/" + person_id + "/enrollments/new";
    var form_content = $.get(form_path, function(data) {
      $("#enrollment_form .form").html(data);
    });
  });

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', institution_people_path(@institution)

app/views/people/parent_search.html.haml
= form_tag(parent_search_institution_person_path(@institution, @person), method: :get) do
  = text_field_tag :name, nil, placeholder: t(".search_by_name", default: "Search by name")
  = submit_tag t("search", default: "Search")
%h4
  = @title
  = t("for", default: "for")
  = @person.name
%ul
  - @people.each do |person|
    %li
      = person.name
      = link_to t(".relate_parent", default: "Relate parent"), relate_parent_institution_person_path(@institution, @person, person), method: :post
      
= link_to t("back", default: "Back"), institution_person_path(@institution, @person)

app/views/people/show.html.haml
.panel
  %h4= @person.name
  %p= @person.email
  %p= time_ago_in_words(@person.date_of_birth) if @person.date_of_birth
  %p 
    = @person.parents.map { |parent| parent.name }
    = link_to t(".relate_parent", default: "Relate parent"), parent_search_institution_person_path(@institution, @person)

= link_to 'Edit', edit_institution_person_path(@institution, @person)
\|
= link_to 'Back', institution_people_path(@institution)