config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :institutions, only: [] do
    resources :people do
      member do
        get "parents/search", action: :parent_search, as: :parent_search
        post "parents/:parent_id", action: :relate_parent, as: :relate_parent
      end
      
      resources :enrollments
    end
    
    resources :grades do
      resources :meetings
    end
  end
  
  get "/" => "application#home"
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :person
  belongs_to :grade
  
  validates :person_id, uniqueness: {scope: :grade_id}
  validates :role, :person_id, :grade_id, presence: true
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_institution
  before_action :set_person
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = @person.enrollments.all
    
    respond_with(@institution, @person, @enrollments)
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
    respond_with(@institution, @person, @enrollment)
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
    
    render :new, layout: false
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = @person.enrollments.new(enrollment_params)
    @enrollment.save

    respond_with(@institution, @person, @enrollment)
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    @enrollment.update(enrollment_params)
    
    respond_with(@institution, @person, @enrollment)
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    
    respond_with(@institution, @person, @enrollment)
  end

  private
    def set_person
      @person = @institution.people.find(params[:person_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = @person.enrollments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:role, :grade_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.haml
%p
  %b Role:
  = @enrollment.role
%p
  %b Grade:
  = @enrollment.grade.name

app/views/enrollments/_form.html.haml
= simple_form_for([@institution, @person, @enrollment], remote: true) do |f|
  = f.error_notification

  .form-inputs
    = f.select :role, ["Evangelizando", "Evangelizador", "Monitor"]
    = f.select :grade_id, @institution.grades.pluck(:name, :id)

  .form-actions
    = f.button :submit

app/views/enrollments/create.js.erb
<%- if @enrollment.valid? %>
  $("#enrollment_form .message").html("<%= escape_javascript(foundation_alert(flash[:notice], type: :success)) %>");
<%- else %>
  $("#enrollment_form .message").html("<%= escape_javascript(foundation_alert(@enrollment.errors.full_messages.first, type: :alert)) %>");
<% end %>

app/views/enrollments/edit.html.haml
%h1 Editing enrollment

= render 'form'

= link_to 'Show', institution_person_enrollment_path(@institution, @person, @enrollment)
\|
= link_to 'Back', institution_person_enrollments_path(@institution, @person)

app/views/enrollments/index.html.haml
%h1 Listing enrollments

%table
  %thead
    %tr
      %th Role
      %th Grade
      %th
      %th
      %th

  %tbody
    - @enrollments.each do |enrollment|
      %tr
        %td= enrollment.role
        %td= enrollment.grade.name
        %td= link_to 'Show', institution_person_enrollment_path(@institution, @person, enrollment)
        %td= link_to 'Edit', edit_institution_person_enrollment_path(@institution, @person, enrollment)
        %td= link_to 'Destroy', institution_person_enrollment_path(@institution, @person, enrollment), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Enrollment', new_institution_person_enrollment_path(@institution, @person)

app/views/enrollments/new.html.haml
%h1 New enrollment

= render 'form'

app/views/enrollments/show.html.haml
= render partial: :enrollment

= link_to 'Edit', edit_institution_person_enrollment_path(@institution, @person, @enrollment)
\|
= link_to 'Back', institution_person_enrollments_path(@institution, @person)